AllCops:

  Exclude:
    - db/**/*
    - config/**/*
    - bin/**/*
    - lib/**/*
    - config.ru
    - Guardfile
    - Rakefile
    - client/**/*
    - Gemfile
    - Gemfile.lock
    - Jenkinsfile
    - vendor/**/*

Style/AlignHash:
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/CollectionMethods:
  Enabled: true

Style/CommentAnnotation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/SingleLineBlockParams:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Enabled: false
